# Generated by Django 5.0.6 on 2024-06-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_add',
            field=models.DateField(),
        ),
    ]
